title = "HTR Knowledge Exchange / Kennisuitwisseling"
# baseURL = "https://marijnkoolen.github.io/HTR-Knowledge-Exchange"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"
publishDir = "docs"
baseURL = "https://marijnkoolen.github.io/HTR-knowledge-exchange/"

DefaultContentLanguage = "nl"
SectionPagesMenu = "main"
Pagination.pagerSize = 20
googleAnalytics = ""
enableRobotsTXT = true

[languages]
[languages.en]
title = "HTR Knowledge Exchange"
weight = 2
contentDir = "content/en"
# languageDirection = 'rtl' for Right-To-Left languages
[languages.nl]
title = "HTR Kennisuitwisseling"
weight = 1
contentDir = "content/nl"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 20

[[params.ananke_socials]]
# name = "LinkedIn"
# url = "https://linkedin.com/HTR-knowledge-exchange"
